#!/usr/bin/env bash
#a script that gives information about a domain

print_domain_info() {
    SUBDOMAIN=$1
    DOMAIN=$2
    RECORD=$(dig $SUBDOMAIN.$DOMAIN | awk '/ANSWER SECTION/{getline; print}' | awk '{print $4}')
    IP=$(dig $SUBDOMAIN.$DOMAIN | awk '/ANSWER SECTION/{getline; print}' | awk '{print $5}')
    echo "The subdomain $SUBDOMAIN is a $RECORD record and points to $IP"
    }


DOMAIN=$1
SUBDOMAIN=$2
# Entry point
# if only variable $1 (DOMAIN name)
if [ -z "$SUBDOMAIN" ]
then
    # print info for all submodules
    print_domain_info "www" "$DOMAIN"
    print_domain_info "lb-01" "$DOMAIN"
    print_domain_info "web-01" "$DOMAIN"
    print_domain_info "web-02" "$DOMAIN"
else
    # print info for subdomain in $SUBDOMAIN
    print_domain_info "$SUBDOMAIN" "$DOMAIN"
fi
